### ISSUE TITLE
Create a Docker image for Artichoke build

### ISSUE THREAD

**Issue by lopopolo** [artichoke/docker-artichoke-nightly#1]
We spend a lot of time installing dependencies in the Artichoke build:

https://github.com/artichoke/artichoke/blob/2c6614ca57364b9a574c44be18f3323d08931f25/.circleci/config.yml#L38-L67

The Rust toolchain does not change frequently, neither does the C toolchain, nor the Ruby toolchain.

Build a Docker image with the following dependencies:

- snapshot clang
- bison
- gperf
- binutils
- Rust version that matches the `rust-toolchain`
  - rustfmt, clippy
  - wasm32-unknown-emscripten and wasm32-unknown-unknown targets
- Ruby 2.6.3
- latest Bundler 2.x
- node LTS
- yarn
- shellcheck
- shfmt

This change would enable:

- Implementing the shellcheck file discovery with shfmt, which enables naming shell scripts without the `.sh` suffix.
- Building `mruby-sys` with the clang native `wasm` target.
- Unifying the build into one mega job (not sure if this is desirable).

**Comment by Temikus** [comment]
@lopopolo Fantastic, thanks for answering my questions! :)

> @Temikus would you like me to give you push access to https://github.com/artichoke/docker-artichoke-nightly?

Sure! I'll still prefer doing all my changes through reviewed PR's if you don't mind as I want to get your input. I promise not to spam you with typo edits tho :)

**Comment by Temikus** [comment]
One small follow-up question - are there any limits on GH Actions I should keep in mind? I took a quick look and didn't see any minute limits for OSS (except for 58-minute per workflow one), but wanted to check with you just to be sure.

**Comment by lopopolo** [comment]
Ok if that’s the case let’s have you send PRs from a fork.

All public repos have no limits on Actions minutes 💪

**Comment by lopopolo** [comment]
Closed in GH-3 and GH-4.
