### ISSUE TITLE
Important: Docker is sunsetting Free Team organizations

### ISSUE THREAD

**Issue by lopopolo** [artichoke/docker-artichoke-nightly#141]
I got the below email from Docker, I believe regarding the `artichokeruby` organization on Docker Hub:

> **Docker is sunsetting Free Team organizations**
>
> Free Team organizations are a legacy subscription tier that no longer exists. This tier included many of the same features, rates, and functionality as a paid Docker Team subscription.
>
> After reviewing the list of accounts that are members of legacy Free Team organizations, we’ve identified yours as potentially being one of them.
>
> If you own a legacy Free Team organization, access to paid features — including private repositories — will be suspended on **April 14, 2023 (11:59 pm UTC)**. Upgrade your subscription before **April 14, 2023** to continue accessing your organization.
>
> If you don’t upgrade to a paid subscription, Docker will retain your organization data for 30 days, after which it will be subject to deletion. During that time, you will maintain access to any images in your public repositories, though rate limitations will apply. At any point during the 30-day period, you can restore access to your organization account if you upgrade to a paid subscription. Visit our [FAQ](https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf) for more information.

## Details

<details>

<summary> Screenshots of FAQ </summary>

![image](https://user-images.githubusercontent.com/860434/225171747-f0458369-73da-4c6e-a980-b298cd00934d.jpeg)

![image](https://user-images.githubusercontent.com/860434/225171786-90c360db-d4ec-4515-b70b-75441204141c.jpeg)

</details>
<details>

<summary> Screenshots of Pricing </summary>

![image](https://user-images.githubusercontent.com/860434/225171825-fb26117a-2087-4601-94eb-04dc3c7f1621.jpeg)

</details>

**Comment by lopopolo** [comment]
The existing `artichokeruby` Docker Hub team has two users: me and a CI machine user.

I don't intend to buy a team subscription, which has a minimum of 5 seats.

@b-n Would you be able to take a look into what it would take to transition this repository to publish to the GitHub Container Registry? I'm not sure if this is relevant, but @artichoke is a paid GitHub Teams organization.

**Comment by b-n** [comment]
Yep, I'll have a look see!

Just a quick note from the beginning, this would immediately limit the people using these packages to having a github account: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry (e.g. they need a PAT with `read:packages` at least).

I'll do a bit of research though, and see what migration options there are though!

**Comment by lopopolo** [comment]
Linking:

- https://github.com/docker/hub-feedback/issues/2314
- https://news.ycombinator.com/item?id=35154025
- https://news.ycombinator.com/item?id=35166317

**Comment by b-n** [comment]
That's a fairly big oof.

Good news, publishing to github packages looks fairly straight forward. I'll prep some PRs in the coming day(s).

**Comment by Vad1mo** [comment]
If, for some reason, the Docker-Sponsored Open-Source Program isn't working out, we are happy to help you out. We operate a Harbor-based [container registry as a service ](https://container-registry.com/)that has many benefits over most of the other registries out there.

There are also features regarding containerized image distribution, that might be valuable too as well.

**Comment by lopopolo** [comment]
I forgot to mention, all of this is documented here: https://github.com/artichoke/project-infrastructure/blob/trunk/docs/docker-hub-accounts.md

**Comment by lopopolo** [comment]
New updates:

- https://news.ycombinator.com/item?id=35187250
- https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/

**Comment by lopopolo** [comment]
The approach mentioned in this article is pretty cool. I think we could setup such a facade using an empty S3 bucket, CloudFront and CloudFront functions.

- https://httptoolkit.com/blog/docker-image-registry-facade/
- https://github.com/httptoolkit/docker-registry-facade

**Comment by b-n** [comment]
Oooo these are all nice things.

Curious, for the interim, do you want to apply for DSOS? It at least stops the immediate issue.

I think this ticket should still stay open though. The idea of "host your own registry" sounds fairly trivial if I'm looking at what they did in that link. My immediate thoughts are that the redirects in theory shouldn't be needed at all so long as the hashed object can be delivered directly from the `/v2/library/nginx/blobs/sha256:$HASH` which should be achievable by storing the objects directly like that in S3 :thinking:

What was your thought/reasoning on using the CloudFront functions? I can see a need for returning the correctly formatted `HEAD` result with the correct hash etc. I assume knowing which "tag => hash" could just be another object stored in s3 too, and using this cloudfront function for reformatting the response. Yeah?

**Comment by b-n** [comment]
FYI, Started working on a Cloudfront backed S3 Registry here: https://github.com/b-n/s3-docker-registry

If this is sustainable and if Artichoke would like it, then I'd be happy to bring this into Artichoke repos (terraform module?) instead of my private github.

**Comment by lopopolo** [comment]
Been chatting with @b-n on discord. His CloudFront + S3 docker registry looks pretty nice. Together with `docker buildx` and some Python glue this looks pretty maintainable, cheap, and allows us to own our infra.

I've been purging images from Docker Hub to ensure I don't leave anything behind when they lock the image. As of 2 hours ago, the artichokeruby/artichoke repository on Docker Hub had 3502 tags.

I went to https://hub.docker.com/repository/docker/artichokeruby/artichoke/tags?page=1&ordering=last_updated and deleted all tags from 2020, 2021, and 2022. According to the UI all of these tags were "Inactive Image".

As of now, the repository on Docker Hub has about 150 tags.

I plan to push a PR which stops tagging images with the Git SHA of the artichoke/artichoke repo the Artichoke binaries are sourced from which should cut down on the spam.

TODO: update the README on Docker Hub to redirect to the new place we host the images.

**Comment by lopopolo** [comment]
> Curious, for the interim, do you want to apply for DSOS? It at least stops the immediate issue.

I don't think I responded to this directly. No, I am not interested in applying to DSOS.

**Comment by lopopolo** [comment]
> I plan to push a PR which stops tagging images with the Git SHA of the artichoke/artichoke repo the Artichoke binaries are sourced from which should cut down on the spam.

Done:

- https://github.com/artichoke/docker-artichoke-nightly/pull/142

**Comment by lopopolo** [comment]
I just got this email from Docker:

> ## We’re no longer sunsetting Free Team organizations
>
> On March 14, 2023, we emailed you about your Free Team subscription, outlining our intention to sunset that plan. After listening to the concerns of the community, we’ve decided to reverse course, and are no longer sunsetting the Free Team plan. 
>
> If you’re currently on the Free Team plan, you no longer have to migrate to another plan by April 14. All customers who upgraded to a paid subscription will automatically receive a full refund for the transaction in the next 30 days, allowing them to use their new paid subscription for free for the duration of the term they purchased. 
>
> We apologize for the alarm our decision caused. For more details, please visit our FAQ.

## FAQ

The following FAQ blog post was linked from the email:

https://www.docker.com/developers/free-team-faq/

<details>

<summary> Blog Post </summary>

> # Free Team Organizations FAQ
>
> >As of March 24, 2023, Docker has reversed its decision to sunset the “Docker Free Team” plan. Read on for details.
>
> ## Is Docker sunsetting the Free Team plan?
>
> No. Docker communicated its intent to sunset the Docker Free Team plan on March 14, 2023, but this decision was reversed on March 24, 2023.
>
> ## Were other Docker offerings ever impacted?
>
> No. There was no impact to Docker Personal, Docker Pro, Docker Team, Docker Business, Docker-Sponsored Open Source, Docker Verified Publishers, or Docker Official Images.
>
> ## Does Docker still have an Open Source program?
>
> Yes. Our long-standing Docker-Sponsored Open Source program was never affected by the (now-reversed) sunsetting of Free Team plans, and continues to be available. We recommend eligible projects apply to this program, as it offers benefits that exceed those of the Free Team plan.
>
> ## How do I know if I’m using the Docker Free Team plan?
>
> Please consult the Organizations page of your Docker account: organizations using the Free Team plan are labeled “Docker Free Team” in the “Subscription” column. Less than 2% of Docker users have a Free Team organization on their account.
>
> ## Why is Docker Free Team not on the pricing page right now?
>
> We removed this plan as a signup option in 2021.
>
> ## What’s the difference between the (paid) Docker Team plan and the Docker Free Team plan?
>
> The main advantages of (paid) Docker Team vs. Docker Free Team are:
>
> - Unlimited number of teams (vs. 1 team in Free Team)
> - Up to 100 seats total (vs. 3 seats max in Free Team)
> - Unlimited private repositories (vs. no private repositories included in Free Team)
> - 5,000 pulls/day/user (vs. 200 pulls/6 hours/user in Free Team)
> - The Free Team plan does not include a license for commercial use of Docker Desktop at a company of more than 250 employees OR more than $10 million in annual revenue.
>
> ## What if I exceed the limits of the Docker Free Team plan?
>
> If you need more than what Docker Free Team offers, you should upgrade to Docker Team or Docker Business.
>
> ## What if I requested a migration from Docker Free Team to Docker Personal or Docker Pro?
>
> We will not migrate your account, as you can now continue to use your current Free Team organization. Our support team will respond to all open inquiries to confirm this.
>
> ## I upgraded from Docker Free Team to a paid plan between March 14 and March 24, when will I receive my refund?
>
> We are working to identify and refund all such transactions that happened between our announcements on March 14 and March 24. Please allow up to 30 days to receive your refund.
>
> ## I upgraded from Docker Free Team to a paid plan, but I’m having issues reverting to Free Team.
>
> Please contact support.
>
> ## Can I export the data from my account?
>
> Yes, you may pull images from your private repositories on the Docker registry and push those images to another registry of your choosing.
>
> ## Is Docker removing any public images or layers?
>
> No. At no point did Docker intend to delete, or in any way limit access to public repositories. No action is required for open source project maintainers. Public images or layers only disappear from Docker Hub if the maintainer of the repository decides to delete them from Docker Hub.
>
> ## Can someone else “squat” namespaces?
>
> No. Docker did not release namespaces, so users were never at risk of having namespaces "squatted."
>
> ## Did this impact the security of content on Docker Hub?
>
> No. At no point did Docker restrict access to public repositories. Maintainers have been able to update their repositories without interruption, and continue to have full access to their repositories for any purpose, such as remediating CVEs.
>
> ## What if I still have questions?
>
> Please contact support.

</details>

**Comment by b-n** [comment]
Pressure is slightly off, but let's get this private registry thing working!

In theory we can do things like `docker pull docker.artichoke.org/nightly:latest` (e.g. just calling the image `nightly` or `stable`). Not sure if we want to, but we could!

I'm curious, would you want to move the ownership of my `s3-docker-registry` module to artichoke? I always trust packages/modules/etc more when they are owned by an organization rather than an individual. Doesn't bother me either way though.

**Comment by lopopolo** [comment]
Docker walked back these changes. Closing this as no longer required.
