### ISSUE TITLE
Automate bumping `RUST_VERSION`

### ISSUE THREAD

**Issue by lopopolo** [artichoke/docker-artichoke-nightly#192]
The Rust team comes out with a new version of the compiler every 6 weeks (sometimes sooner in the case of patch releases).

These releases are announced on the Rust blog as well as via GitHub Releases. Minor releases, e.g. Rust 1.75.0, always drop on Thursdays.

I wonder if there is something like an RSS feed or some magic we can run on a cron by querying the GitHub API to pull the latest released version of the compiler, update the `Rakefile`, run `bundle exec rake toolchain:sync`, commit + push + open a PR.

This is how `generate_third_party` does this: https://github.com/artichoke/generate_third_party/blob/9c76d24d2276cba48c1b90032837d6c59cdda7b9/lib/generate_third_party/cargo_about/platform.rb#L28-L50

**Comment by lopopolo** [comment]
@b-n let me know if you'd be interested in taking this

**Comment by b-n** [comment]
@lopopolo Ooooooo yes! That is for sure doable. That `generate_third_party` code is essentially what I was thinking, so can lift and shift some of it.

You're thinking specifically for this repo and thus something that automates this right: https://github.com/artichoke/docker-artichoke-nightly/commit/83d0303e52170a6c8a8107fb642a874eeb873303 ?

**Comment by lopopolo** [comment]
Yup yup!
